In [3]:
#1.Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise 
# addition, subtraction, multiplication, and division to compare their activity levels.
import numpy as np

friend1=np.array([4500,3500,3000,2000,4000,2800,4500])
friend2=np.array([2500,3500,3000,4500,2800,2000,4000])

addition=friend1 + friend2
subtraction=friend1 - friend2
multiplication=friend1 * friend2
divison=friend1 / friend2

print("addition of daily step counts:", addition)
print("subtraction of daily step counts:", subtraction)
print("multiplication of daily step counts:", multiplication)
print("division of daily step counts:", divison)






addition of daily step counts: [7000 7000 6000 6500 6800 4800 8500]
subtraction of daily step counts: [ 2000     0     0 -2500  1200   800   500]
multiplication of daily step counts: [11250000 12250000  9000000  9000000 11200000  5600000 18000000]
division of daily step counts: [1.8        1.         1.         0.44444444 1.42857143 1.4
 1.125     ]


In [11]:
#2.Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction
# scores (user preferences and song popularity), use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.
import numpy as np

user_preferences=np.array([[1,2,4],
                          [2,3,5],
                          [3,4,1]])

song_popularity=np.array([[5,4,3],
                         [4,3,2],
                         [3,2,1]])

recommendation_dot=np.dot(user_preferences,song_popularity)

recommendation_matmul=np.matmul(user_preferences,song_popularity)

print("recommendation matrix using dot():")
print(recommendation_dot)

print("\nrecommendation matrix using matmul():")
print(recommendation_matmul)

print("\nare both results same?")
print(np.array_equal(recommendation_dot,recommendation_matmul))

#The np.dot() and np.matmul() functions are used to perform matrix multiplication and calculate the final
# recommendation matrix. Since both inputs are 2D matrices, dot() and matmul() produce the same result.

recommendation matrix using dot():
[[25 18 11]
 [37 27 17]
 [34 26 18]]

recommendation matrix using matmul():
[[25 18 11]
 [37 27 17]
 [34 26 18]]

are both results same?
True


In [26]:
#3.Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T)
# to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values.
import numpy as np

image=np.array([  [20, 40, 60, 80],
                  [30, 50, 70, 90],
                  [40, 60, 80, 100],
                  [50, 70, 90, 110]
])

rotated_image=image.T

print(rotated_image)
print("mean:", rotated_image.mean())
print("median:", np.median(rotated_image))
print("standard deviation:", rotated_image.std())
print("variance:", rotated_image.var())

[[ 20  30  40  50]
 [ 40  50  60  70]
 [ 60  70  80  90]
 [ 80  90 100 110]]
mean: 65.0
median: 65.0
standard deviation: 25.0
variance: 625.0


In [ ]:
#4.Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), 
# np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong> If the matrix is not invertible, modify one value and try again.</em>
import numpy as np

rating=np.array([ [4, 2, 1],
                  [2, 5, 2],
                  [1, 2, 4]])

inverse=np.linalg.inv(rating)
determinant=np.linalg.det(rating)
eigenvalues, eigenvectors=np.linalg.eig(rating)

print("inverse of the rating matrix:",inverse)
print("determinant of the rating matrix:",determinant)
print("eigenvalues:", eigenvalues)
print("eigenvectors:", eigenvectors)



inverse of the rating matrix: [[ 0.31372549 -0.11764706 -0.01960784]
 [-0.11764706  0.29411765 -0.11764706]
 [-0.01960784 -0.11764706  0.31372549]]
determinant of the rating matrix: 51.0
eigenvalues: [7.82842712 3.         2.17157288]
eigenvectors: [[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [-7.07106781e-01 -6.71096257e-16 -7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]


In [ ]:
#5.Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days.
# Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.
import numpy as np

orders=np.array([ [100, 120, 90, 110, 130, 140],
                  [80, 100, 95, 105, 115, 125]])

reshaped=orders.reshape(3,4)
flattened=reshaped.flatten()
part1,part2=np.split(flattened,2)
stacked=np.vstack((part1,part2))

print("reshaped array:",reshaped)
print("flattened array:",flattened)
print("part1:",part1)
print("part2:",part2)
print("stacked array:",stacked)

reshaped array: [[100 120  90 110]
 [130 140  80 100]
 [ 95 105 115 125]]
flattened array: [100 120  90 110 130 140  80 100  95 105 115 125]
part1: [100 120  90 110 130 140]
part2: [ 80 100  95 105 115 125]
stacked array: [[100 120  90 110 130 140]
 [ 80 100  95 105 115 125]]
